services:
  - type: web
    name: repotech-telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.2
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: UPI_ID
        sync: false
